import Head from 'next/head'
import { useState } from 'react'


export default function Home() {
  let onHandleSubmit = async(e)=>{
    e.preventDefault();
    if(firstName.length === 0){
      setErrFirstName("This field is required");
      return false;
    }else if(firstName.includes(" ")){
      setErrFirstName("Spaces are not allowed.");
      return false;
    } else if(/[0-9]/.test(firstName)){
      setErrFirstName("Firstname can't contain any number")
      return false;
    } else{
      setErrFirstName("");
      if(lastName.length === 0){
        setErrLastName("This field is required");
        return false;
      } else if(/[0-9]/.test(lastName)){
        setErrLastName("Lastname can't contain any number")
        return false;
      } else {
        setErrLastName("");
        if(!phoneNumber.match(/^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/im)){
          setErrPhoneNumber("Phone number is not valid")
          return false;
        } else{
          setErrPhoneNumber("");
          if(!email.match(/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/))
          {
            setErrEmail("Email is not valid")
            return false;
          } else{
            setErrEmail("");
          }
        }
      }
    }
     const res = await fetch("/api/form",{
        body: JSON.stringify({
            first_name: firstName,
            last_name: lastName,
            ph_no: phoneNumber,
            email: email
        }),
        headers: {
            'content-Type' : 'application/json'
        },
        method: 'POST'
    })
    
    const result = await res.json();
    if(result.success===true){
        setData(result.status);
    } else {
      setData(result.status);
    }
}
const [data, setData] = useState(null);
const [firstName,setFirstName] = useState("")
const [lastName,setLastName] = useState("")
const [phoneNumber,setPhoneNumber] = useState("")
const [email,setEmail] = useState("");
const [errFirstName,setErrFirstName] = useState("");
const [errLastName,setErrLastName] = useState("");
const [errPhoneNumber,setErrPhoneNumber] = useState("");
const [errEmail,setErrEmail] = useState("");


  return (
    <div className="container my-5">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"></link>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></script>
      </Head>
      {data && <div className="alert alert-success alert-dismissible fade show" role="alert">
            {data}
            <button type="button" className="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>}
      <h1 style={{textAlign:"center"}}>Contact form</h1>        
      <form onSubmit={onHandleSubmit}>
          <label htmlFor="first_name">First Name</label>
          <input type="text" onChange={(e)=>{setFirstName(e.target.value)}}  name='first_name' id='first_name' className='form-control' width={100}/>
          <p className='text-danger'>{errFirstName}</p>
          <br/>
          <label htmlFor="last_name">Last Name</label>
          <input type="text" onChange={(e)=>{setLastName(e.target.value)}} name='last_name' id='last_name' className='form-control' width={100}/>
          <p className='text-danger'>{errLastName}</p>
          <br/>
          <label htmlFor="ph_no">Phone Number</label>
          <input type="text" onChange={(e)=>{setPhoneNumber(e.target.value)}} name='ph_no' id='ph_no' className='form-control' width={100}/>
          <p className='text-danger'>{errPhoneNumber}</p>
          <br/>
          <label htmlFor="email">Email</label>
          <input type="text" onChange={(e)=>{setEmail(e.target.value)}} name='email' id='email' className='form-control' width={100}/>
          <p className='text-danger'>{errEmail}</p>
          <br/>
          <button type="submit" className='btn btn-success'>Submit</button>
      </form>
    </div>
  )
}
